version: "3.8"
services:

  # httpd-Apache
  php:
    build:
      context: ./docker/httpd/
      dockerfile: Dockerfile
      args:
        - USERNAME=${APP_CONTAINER_USERNAME}
        - UID=${APP_CONTAINER_UID}
        - GID=${APP_CONTAINER_GID}
    user: ${APP_CONTAINER_USERNAME}:${APP_CONTAINER_USERNAME}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_DEFAULT_PORT}
    volumes:
      - ./:/var/www/html
    env_file:
      - docker/httpd/httpd.env

  # Database
  db:
    build:
      dockerfile: ./docker/mysql/Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - ${DB_DEFAULT_PORT}
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${DATABASE_NAME}

volumes:
  db-volume: