services:

  # httpd-Apache
  typo3:
    build:
      context: ./docker/httpd/
      dockerfile: Dockerfile
      target: ${BUILD_TARGET_APP_DEV}
      args:
        - USERNAME=${APP_CONTAINER_USERNAME}
        - UID=${APP_CONTAINER_UID}
        - GID=${APP_CONTAINER_GID}
    user: ${APP_CONTAINER_USERNAME}:${APP_CONTAINER_USERNAME}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT_1}
      - ${APP_PORT_2}
    volumes:
      - ./src:/var/www/html
      - ./docker/httpd/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    env_file:
      - docker/httpd/env/httpd.env
#      - docker/httpd/env/extra.env # more info in README file

  # Database
  db:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
      args:
        - USERNAME=${APP_CONTAINER_USERNAME}
        - UID=${APP_CONTAINER_UID}
        - GID=${APP_CONTAINER_GID}
    user: ${APP_CONTAINER_USERNAME}:${APP_CONTAINER_USERNAME}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./docker/mysql/db-volume:/var/lib/mysql
    ports:
      - ${DB_PORT}
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
