services:

  # httpd-Apache
  typo3:
    build:
      context: ./docker/httpd/
      dockerfile: Dockerfile
      args:
        - USERNAME=${APP_CONTAINER_USERNAME}
        - UID=${APP_CONTAINER_UID}
        - GID=${APP_CONTAINER_GID}
    user: ${APP_CONTAINER_USERNAME}:${APP_CONTAINER_USERNAME}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_DEFAULT_PORT}
    volumes:
      - ./src:/var/www/html
    env_file:
      - docker/httpd/env/httpd.env
      - docker/httpd/env/extra.env

  # Database
  db:
    build:
      dockerfile: ./docker/mysql/Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - ${DB_DEFAULT_PORT}
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

volumes:
  db-volume:
